version: "3.9"

services:
  prosody:
    image: jitsi/prosody:stable-8922
    restart: unless-stopped
    env_file:
      - ./jitsi/.env
    volumes:
      - jitsi-config:/config
      - jitsi-prosody:/prosody
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5347:5347"

  web:
    image: jitsi/web:stable-8922
    restart: unless-stopped
    env_file:
      - ./jitsi/.env
    depends_on:
      - prosody
      - jicofo
    ports:
      - "8086:80"
      - "8445:443"
    volumes:
      - jitsi-config:/config
      - jitsi-web:/usr/share/jitsi-meet

  jicofo:
    image: jitsi/jicofo:stable-8922
    restart: unless-stopped
    env_file:
      - ./jitsi/.env
    depends_on:
      - prosody
    volumes:
      - jitsi-config:/config

  jvb:
    image: jitsi/jvb:stable-8922
    restart: unless-stopped
    env_file:
      - ./jitsi/.env
    depends_on:
      - prosody
    ports:
      - "10000:10000/udp"
      - "4443:4443"
    volumes:
      - jitsi-config:/config

volumes:
  jitsi-config:
  jitsi-prosody:
  jitsi-web:
