version: "3.9"

services:
  synapse:
    image: matrixdotorg/synapse:1.107.0
    restart: unless-stopped
    environment:
      - SYNAPSE_SERVER_NAME=matrix.localhost
      - SYNAPSE_REPORT_STATS=yes
      - SYNAPSE_ENABLE_REGISTRATION=yes
      - SYNAPSE_NO_TLS=yes
      - SYNAPSE_EVENT_CACHE_SIZE=10K
      - POSTGRES_PASSWORD=synapse
      - POSTGRES_USER=synapse
      - POSTGRES_DATABASE=synapse
      - POSTGRES_HOST=synapse-postgres
    volumes:
      - synapse-data:/data
    depends_on:
      - synapse-postgres
    ports:
      - "8008:8008"

  element:
    image: vectorim/element-web:1.11.68
    restart: unless-stopped
    ports:
      - "8085:80"
    environment:
      - MATRIX_SERVER_URL=http://localhost:8008
      - MATRIX_SERVER_NAME=matrix.localhost
    volumes:
      - element-config:/app/config

  synapse-postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=synapse
      - POSTGRES_DB=synapse
    volumes:
      - synapse-postgres:/var/lib/postgresql/data

volumes:
  synapse-data:
  element-config:
  synapse-postgres:
