version: "3.9"

services:
  wire-server:
    image: quay.io/wire/wire-server:2.112.0
    restart: unless-stopped
    environment:
      - WIRE_DB_HOST=wire-postgres
      - WIRE_DB_USER=wire
      - WIRE_DB_PASSWORD=wirepass
      - WIRE_DB_NAME=wire
      - WIRE_REDIS_HOST=wire-redis
      - WIRE_BASE_URL=https://wire.localhost
      - WIRE_ADMIN_EMAIL=admin@wire.localhost
      - WIRE_ADMIN_PASSWORD=Admin123!
      - WIRE_SERVER_PORT=8080
    depends_on:
      - wire-postgres
      - wire-redis
    volumes:
      - wire-config:/opt/wire-server/config

  wire-nginx:
    image: nginx:1.25-alpine
    restart: unless-stopped
    depends_on:
      - wire-server
    ports:
      - "8446:443"
    volumes:
      - ./wire/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - wire-certs:/etc/ssl/private
    command: >-
      /bin/sh -c "if [ ! -f /etc/ssl/private/selfsigned.crt ]; then \
        openssl req -x509 -nodes -subj '/CN=wire.localhost' -days 365 -newkey rsa:2048 \
          -keyout /etc/ssl/private/selfsigned.key \
          -out /etc/ssl/private/selfsigned.crt; \
      fi && nginx -g 'daemon off;'"

  wire-postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=wire
      - POSTGRES_USER=wire
      - POSTGRES_PASSWORD=wirepass
    volumes:
      - wire-postgres:/var/lib/postgresql/data

  wire-redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - wire-redis:/data

volumes:
  wire-config:
  wire-certs:
  wire-postgres:
  wire-redis:
