version: "3.9"

services:
  nextcloud:
    image: nextcloud:27-apache
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - POSTGRES_HOST=nextcloud-db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloudpass
      - REDIS_HOST=nextcloud-redis
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=adminpass
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    volumes:
      - nextcloud-data:/var/www/html
      - nextcloud-apps:/var/www/html/custom_apps
      - nextcloud-config:/var/www/html/config
      - nextcloud-data-files:/var/www/html/data

  nextcloud-db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloudpass
    volumes:
      - nextcloud-db:/var/lib/postgresql/data

  nextcloud-redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - nextcloud-redis:/data

volumes:
  nextcloud-data:
  nextcloud-apps:
  nextcloud-config:
  nextcloud-data-files:
  nextcloud-db:
  nextcloud-redis:
