services:
  loki:
    image: grafana/loki:2.9.4
    command: ["-config.file=/etc/loki/local-config.yaml"]
    ports:
      - 3100:3100
    networks: [lab]

  promtail:
    image: grafana/promtail:2.9.4
    command: ["-config.file=/etc/promtail/config.yml"]
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
      - ../charts/master-nginx/logs:/var/log/nginx:ro
      - ../../datasets/data/logs:/data/logs:ro
    networks: [lab]
    depends_on: [loki]

  grafana:
    image: grafana/grafana-oss:10.3.1
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
    volumes:
      - grafana-data:/var/lib/grafana
    networks: [lab]
    depends_on: [loki]

networks:
  lab:
    external: true
    name: learning-lab_docker_core_lab

volumes:
  grafana-data:
