server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

targets:
  - job_name: nginx-access
    static_configs:
      - targets: [localhost]
        labels:
          job: nginx
          __path__: /var/log/nginx/*.log
  - job_name: dataset-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: cicids
          __path__: /data/logs/*.log
