apiVersion: v1
kind: Service
metadata:
  name: {{ include "photoprism.fullname" . }}
  labels:
    {{- include "photoprism.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "photoprism.selectorLabels" . | nindent 4 }}
