services:
  airflow:
    image: apache/airflow:2.8.1-python3.11
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
    command: bash -c "airflow db migrate && airflow users create --username admin --password admin --firstname Air --lastname Flow --role Admin --email admin@example.com && airflow webserver & airflow scheduler"
    volumes:
      - ./dags:/opt/airflow/dags
      - ../../datasets/data:/opt/airflow/data:ro
    ports:
      - 8082:8080
    networks: [lab]

networks:
  lab:
    external: true
    name: learning-lab_docker_core_lab
