# Notes: Supports Postgres, MySQL, or SQLite; Postgres recommended.
services:
  navidrome:
    image: deluan/navidrome:0.50.2
    container_name: navidrome
    restart: unless-stopped
    ports:
      - "4533:4533"
    environment:
      # TODO: define environment variables
    networks:
      - lab

networks:
  lab:
    external: true
    name: learning-lab_lab
