# Notes: Stateless streaming server; persist /app/data.
services:
  owncast:
    image: owncast/owncast:0.1.3
    container_name: owncast
    restart: unless-stopped
    ports:
      - "8096:8096"
    environment:
      # TODO: define environment variables
    networks:
      - lab

networks:
  lab:
    external: true
    name: learning-lab_lab
