# Notes: Supports SQLite for demos; Postgres recommended.
services:
  label-studio:
    image: heartexlabs/label-studio:1.11.0
    container_name: label-studio
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      # TODO: define environment variables
    networks:
      - lab

networks:
  lab:
    external: true
    name: learning-lab_lab
