# Notes: Needs Postgres and Redis plus a worker container.
services:
  redash:
    image: redash/redash:10.1.0.b50633
    container_name: redash
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      # TODO: define environment variables
    networks:
      - lab

networks:
  lab:
    external: true
    name: learning-lab_lab
