# Notes: Pair with Zabbix web container and Postgres database.
services:
  zabbix:
    image: zabbix/zabbix-server-pgsql:7.0-ubuntu
    container_name: zabbix
    restart: unless-stopped
    ports:
      - "10051:10051"
    environment:
      # TODO: define environment variables
    networks:
      - lab

networks:
  lab:
    external: true
    name: learning-lab_lab
