# Notes: Pair with Gravitee gateway, API, MongoDB, and Elasticsearch services.
services:
  gravitee-api-management:
    image: graviteeio/apim-management-ui:4.4.0
    container_name: gravitee-api-management
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      # TODO: define environment variables
    networks:
      - lab

networks:
  lab:
    external: true
    name: learning-lab_lab
