# Notes: Ingest and query endpoints share same port.
services:
  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.101.0
    container_name: victoriametrics
    restart: unless-stopped
    ports:
      - "8428:8428"
    environment:
      # TODO: define environment variables
    networks:
      - lab

networks:
  lab:
    external: true
    name: learning-lab_lab
