# Notes: Requires Postgres and Redis; mount data and media directories.
services:
  paperless-ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.7.2
    container_name: paperless-ngx
    restart: unless-stopped
    ports:
      - "8093:8093"
    environment:
      # TODO: define environment variables
    networks:
      - lab

networks:
  lab:
    external: true
    name: learning-lab_lab
