apiVersion: v1
kind: Service
metadata:
  name: {{ include "odoo-community.fullname" . }}
  labels:
    {{- include "odoo-community.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "odoo-community.selectorLabels" . | nindent 4 }}
