services:
  app:
    build: .
    image: learning-lab/laravel-app:latest
    volumes:
      - ./src:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_URL: http://laravel-app
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: sales
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
      QUEUE_CONNECTION: redis
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      REDIS_HOST: redis
    networks:
      - lab

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./src/public:/var/www/html/public:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - lab
    depends_on:
      - app

  horizon:
    build: .
    command: php artisan horizon
    volumes:
      - ./src:/var/www/html
    environment:
      QUEUE_CONNECTION: redis
      REDIS_HOST: redis
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_DATABASE: sales
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
    networks:
      - lab
    depends_on:
      - app

  artisan:
    build: .
    entrypoint: ["php", "artisan"]
    volumes:
      - ./src:/var/www/html
    networks:
      - lab

networks:
  lab:
    external: true
    name: learning-lab_docker_core_lab
