apiVersion: v1
kind: Service
metadata:
  name: {{ include "tube-archivist.fullname" . }}
  labels:
    {{- include "tube-archivist.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "tube-archivist.selectorLabels" . | nindent 4 }}
