apiVersion: v1
kind: Service
metadata:
  name: {{ include "lemmy.fullname" . }}
  labels:
    {{- include "lemmy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "lemmy.selectorLabels" . | nindent 4 }}
