services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: sales
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks: [lab]

  php:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://symfony:symfony@postgres:5432/sales?serverVersion=16&charset=utf8
    volumes:
      - symfony-var:/var/www/html/var
    networks: [lab]

  nginx:
    image: nginx:1.25-alpine
    depends_on:
      - php
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - symfony-var:/var/www/html/var
      - ./app/public:/var/www/html/public:ro
    ports:
      - 8083:80
    networks: [lab]

networks:
  lab:
    external: true
    name: learning-lab_docker_core_lab

volumes:
  postgres-data:
  symfony-var:
