parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $appName: 'Symfony Sales Orders'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Repository\:
        resource: '../src/Repository'
        public: false
