apiVersion: v1
kind: Service
metadata:
  name: {{ include "komga.fullname" . }}
  labels:
    {{- include "komga.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "komga.selectorLabels" . | nindent 4 }}
