services:
  airbyte-db:
    image: airbyte/db:0.50.11
    environment:
      - POSTGRES_USER=airbyte
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=airbyte
    volumes:
      - airbyte-db-data:/var/lib/postgresql/data

  airbyte-app:
    image: airbyte/bootloader:0.50.11
    ports:
      - 8000:8000
    environment:
      - AIRBYTE_ROLE=main
      - DATABASE_HOST=airbyte-db
      - DATABASE_PORT=5432
      - DATABASE_DB=airbyte
      - DATABASE_USER=airbyte
      - DATABASE_PASSWORD=password
      - CONFIG_ROOT=/data/config
    volumes:
      - airbyte-config:/data/config
    depends_on:
      - airbyte-db

volumes:
  airbyte-db-data:
  airbyte-config:
