services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: sales
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks: [lab]

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    restart: unless-stopped
    environment:
      CLICKHOUSE_DB: analytics
      CLICKHOUSE_USER: analytics
      CLICKHOUSE_PASSWORD: analytics
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    networks: [lab]

  minio:
    image: minio/minio:RELEASE.2024-03-30T00-08-50Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data
    networks: [lab]

  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    networks: [lab]

  nginx-master:
    build: ../charts/master-nginx
    ports:
      - 8080:80
    depends_on:
      - clickhouse
    networks: [lab]

networks:
  lab:
    driver: bridge

volumes:
  postgres-data:
  clickhouse-data:
  minio-data:
  redis-data:
