version: "3.9"

services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://umami:umami@umami-db:5432/umami
      - HASH_SALT=umami-salt
      - PORT=3000
    ports:
      - "80816:3000"
    depends_on:
      - umami-db

  umami-db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=umami
      - POSTGRES_USER=umami
      - POSTGRES_PASSWORD=umami
    volumes:
      - umami-db:/var/lib/postgresql/data

volumes:
  umami-db:
