version: "3.9"

services:
  strapi:
    image: strapi/strapi:latest
    restart: unless-stopped
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=strapi-db
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
      - ADMIN_JWT_SECRET=changeme
      - APP_KEYS=key1,key2
    ports:
      - "1337:1337"
    volumes:
      - strapi-app:/srv/app
    depends_on:
      - strapi-db

  strapi-db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=strapi
      - POSTGRES_USER=strapi
      - POSTGRES_PASSWORD=strapi
    volumes:
      - strapi-db:/var/lib/postgresql/data

volumes:
  strapi-app:
  strapi-db:
