apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "core.fullname" . }}-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "core.fullname" . }}-minio
  template:
    metadata:
      labels:
        app: {{ include "core.fullname" . }}-minio
    spec:
      containers:
        - name: minio
          image: {{ .Values.minio.image }}
          args: ["server", "/data", "--console-address", ":9001"]
          env:
            - name: MINIO_ROOT_USER
              value: {{ .Values.minio.rootUser | quote }}
            - name: MINIO_ROOT_PASSWORD
              value: {{ .Values.minio.rootPassword | quote }}
          ports:
            - containerPort: 9000
            - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "core.fullname" . }}-minio
spec:
  selector:
    app: {{ include "core.fullname" . }}-minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
