apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "core.fullname" . }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "core.fullname" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "core.fullname" . }}-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "core.fullname" . }}-postgres
spec:
  selector:
    app: {{ include "core.fullname" . }}-postgres
  ports:
    - port: 5432
      targetPort: 5432
