apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "core.fullname" . }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "core.fullname" . }}-redis
  template:
    metadata:
      labels:
        app: {{ include "core.fullname" . }}-redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          args: ["redis-server", "--save", "60", "1"]
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "core.fullname" . }}-redis
spec:
  selector:
    app: {{ include "core.fullname" . }}-redis
  ports:
    - port: 6379
      targetPort: 6379
